<?php

return [
    [
        'label' => 'Getting Started',
        'items' => [
            [
                'title' => 'Introduction',
                'path' => '/docs/introduction',
                'description' => 'Get Started with Flexiwind Laravel, a modern Laravel Blade/Livewire Ui Components collection',
                'keywords' => 'Flexiwind, Flexywind, Tailwind, Components, UnifyUI TailwindCSS, Unify, Flexi wind, Flexy wind, UnoForge, TailwindCSS, Tailwind Blocks, Tailwind v4',
                'seoDescription' => 'Learn how to get started with Flexiwind Laravel, a modern collection of Laravel Blade and Livewire UI components built with TailwindCSS.',
            ],
            [
                'title' => 'Installation',
                'path' => '/docs/installation',
                'description' => 'How to install Flexiwind',
                'keywords' => 'Flexiwind, Flexywind, Installation, Flexiwind, Flexywind, Tailwind, Components, UnifyUI TailwindCSS, Unify, Flexi wind, Flexy wind, UnoForge, TailwindCSS, Tailwind Blocks, Tailwind v4',
                'seoDescription' => 'Step-by-step guide on how to install and set up Flexiwind in your Laravel project.',
            ],
            [
                'title' => 'Theming',
                'path' => '/docs/theme',
                'description' => 'Custo',
                'keywords' => 'Flexiwind, Flexywind, Tailwind, Components, UnifyUI TailwindCSS, Unify, Flexi wind, Flexy wind, UnoForge, TailwindCSS, Tailwind Blocks, Tailwind v4',
                'seoDescription' => 'Learn how to customize and theme your Flexiwind components to match your project\'s design system.',
            ],
            [
                'title' => 'Buttons utilities',
                'path' => '/docs/theme/buttons',
                'description' => 'Comprehensive guide to Flexiwind button styles and variants',
                'keywords' => 'Flexiwind buttons, button variants, button styles, button customization, ',
                'seoDescription' => 'Explore Flexiwind\'s button utilities and learn how to create custom button styles and variants.',
            ],
            [
                'title' => 'UI utilities',
                'path' => '/docs/theme/utilities',
                'description' => 'Utilities',
                'keywords' => 'Flexiwind, Flexywind, Tailwind, Components, UnifyUI TailwindCSS, Unify, Flexi wind, Flexy wind, UnoForge, TailwindCSS, Tailwind Blocks, Tailwind v4',
                'seoDescription' => 'Discover Flexiwind\'s utility classes for building consistent and responsive user interfaces.',
            ],
        ],
    ],
    [
        'label' => 'Components',
        'items' => [
            [
                'title' => 'Accordion',
                'path' => '/components/accordion',
                'description' => 'Expandable content container.',
                'keywords' => 'accordion, collapse, expand, accordion Component, Flexiwind, Flexywind, Tailwind, Components, UnifyUI TailwindCSS, Unify, Flexi wind, Flexy wind, UnoForge, TailwindCSS, Tailwind Blocks, Tailwind v4',
                'seoDescription' => 'Learn how to use Flexiwind\'s accordion component to create expandable content sections.',
            ],
            [
                'title' => 'Alert',
                'path' => '/components/alert',
                'description' => 'Notification for user.',
                'keywords' => 'alert, notification, warning, success, error, Flexiwind, Flexywind, Tailwind, Components, UnifyUI TailwindCSS, Unify, Flexi wind, Flexy wind, UnoForge, TailwindCSS, Tailwind Blocks, Tailwind v4',
                'seoDescription' => 'Implement user notifications with Flexiwind\'s alert component for various message types.',
            ],
            [
                'title' => 'Alert Dialog',
                'path' => '/components/alert-dialog',
                'description' => 'Modal dialog for notification.',
                'keywords' => 'alert dialog, modal dialog, notification, tailwind Modal Component, Flexiwind, Flexywind, Tailwind, Components, UnifyUI TailwindCSS, Unify, Flexi wind, Flexy wind, UnoForge, TailwindCSS, Tailwind Blocks, Tailwind v4',
                'seoDescription' => 'Create interactive alert dialogs using Flexiwind\'s modal dialog component.',
            ],
            [
                'title' => 'Aspect Ratio',
                'path' => '/components/aspect-ratio',
                'description' => 'Container for maintaining aspect ratio.',
                'keywords' => 'aspect ratio, responsive',
                'seoDescription' => 'Maintain consistent image and video aspect ratios with Flexiwind\'s aspect ratio component.',
            ],
            [
                'title' => 'Avatar',
                'path' => '/components/avatar',
                'description' => 'Image or icon for user.',
                'keywords' => 'avatar, image, icon, user',
                'seoDescription' => 'Display user avatars and profile images with Flexiwind\'s avatar component.',
            ],
            [
                'title' => 'Badge',
                'path' => '/components/badge',
                'description' => 'Label or icon for notification.',
                'keywords' => 'badge, label, icon, notification',
                'seoDescription' => 'Add status indicators and notifications with Flexiwind\'s badge component.',
            ],
            [
                'title' => 'Breadcrumbs',
                'path' => '/components/breadcrumbs',
                'description' => 'Navigation for user.',
                'keywords' => 'breadcrumbs, navigation',
                'seoDescription' => 'Implement navigation breadcrumbs to improve user orientation in your application.',
            ],
            [
                'title' => 'Button',
                'path' => '/components/button',
                'description' => 'Click button for user.',
                'keywords' => 'button, click',
                'seoDescription' => 'Create interactive buttons with various styles using Flexiwind\'s button component.',
            ],
            [
                'title' => 'Card',
                'path' => '/components/card',
                'description' => 'Content container with background and border.',
                'keywords' => 'card, container, background, border',
                'seoDescription' => 'Display content in organized cards with Flexiwind\'s card component.',
            ],
            [
                'title' => 'Checkbox',
                'path' => '/components/checkbox',
                'description' => 'Select multiple options.',
                'keywords' => 'checkbox, select, multiple',
                'seoDescription' => 'Implement multiple selection controls with Flexiwind\'s checkbox component.',
            ],
            [
                'title' => 'Divider',
                'path' => '/components/divider',
                'description' => 'Separator for content.',
                'keywords' => 'divider, separator, content',
                'seoDescription' => 'Add visual separation between content with Flexiwind\'s divider component.',
            ],
            [
                'title' => 'Dropdown',
                'path' => '/components/dropdown',
                'description' => 'Select one option from a list.',
                'keywords' => 'dropdown, select, option, list',
                'seoDescription' => 'Create interactive dropdown menus with Flexiwind\'s dropdown component.',
            ],
            [
                'title' => 'Input',
                'path' => '/components/input',
                'description' => 'Form input for user.',
                'keywords' => 'input, form, user',
                'seoDescription' => 'Build form inputs with various styles using Flexiwind\'s input component.',
            ],
            [
                'title' => 'Kbd',
                'path' => '/components/kbd',
                'description' => 'Keyboard input for user.',
                'keywords' => 'kbd, keyboard, input',
                'seoDescription' => 'Display keyboard shortcuts and commands with Flexiwind\'s kbd component.',
            ],
            [
                'title' => 'Link',
                'path' => '/components/link',
                'description' => 'Link to another page or website.',
                'keywords' => 'link, page, website',
                'seoDescription' => 'Create styled links and navigation elements with Flexiwind\'s link component.',
            ],
            [
                'title' => 'Meter',
                'path' => '/components/meter',
                'description' => 'Progress bar for user.',
                'keywords' => 'meter, progress, bar',
                'seoDescription' => 'Display measurements and progress with Flexiwind\'s meter component.',
            ],
            [
                'title' => 'Modal',
                'path' => '/components/modal',
                'description' => 'Progress bar for user.',
                'keywords' => 'modal, alert-dialog, overlay, message dialog, laravel modal, alpine modal',
                'seoDescription' => 'Create interactive modal dialogs with Flexiwind\'s modal component.',
            ],
            [
                'title' => 'Otp /Pin',
                'path' => '/components/otp',
                'description' => 'OTP input for user.',
                'keywords' => 'otp, input, user',
                'seoDescription' => 'Create OTP input with Flexiwind\'s otp component.',
            ],
            [
                'title' => 'Pagination',
                'path' => '/components/pagination',
                'description' => 'Navigation for multiple pages.',
                'keywords' => 'pagination, navigation, pages',
                'seoDescription' => 'Implement page navigation with Flexiwind\'s pagination component.',
            ],
            [
                'title' => 'Popover',
                'path' => '/components/popover',
                'description' => 'Modal dialog for information.',
                'keywords' => 'popover, modal, information',
                'seoDescription' => 'Add contextual information with Flexiwind\'s popover component.',
            ],
            [
                'title' => 'Progress',
                'path' => '/components/progress',
                'description' => 'Progress bar for user.',
                'keywords' => 'progress, bar, user',
                'seoDescription' => 'Show progress and loading states with Flexiwind\'s progress component.',
            ],
            [
                'title' => 'Radio',
                'path' => '/components/radio',
                'description' => 'Select one option from a list.',
                'keywords' => 'radio, select, option, list',
                'seoDescription' => 'Create single-selection controls with Flexiwind\'s radio component.',
            ],
            [
                'title' => 'Range',
                'path' => '/components/range',
                'description' => 'Input for selecting a range of values.',
                'keywords' => 'range, input, values',
                'seoDescription' => 'Implement range selection inputs with Flexiwind\'s range component.',
            ],
            [
                'title' => 'Select',
                'path' => '/components/select',
                'description' => 'Select one option from a list.',
                'keywords' => 'select, option, list',
                'seoDescription' => 'Create dropdown selection menus with Flexiwind\'s select component.',
            ],
            [
                'title' => 'Skeleton',
                'path' => '/components/skeleton',
                'description' => 'Loading animation for content.',
                'keywords' => 'skeleton, loading, animation, content',
                'seoDescription' => 'Add loading state placeholders with Flexiwind\'s skeleton component.',
            ],
            [
                'title' => 'Slideover',
                'path' => '/components/slideover',
                'description' => 'Modal dialog for information.',
                'keywords' => 'slideover, modal, information',
                'seoDescription' => 'Create slide-in panels with Flexiwind\'s slideover component.',
            ],
            [
                'title' => 'Switch',
                'path' => '/components/switch',
                'description' => 'A toggle switch for turning an option on or off, styled for accessibility and ease of use.',
                'keywords' => 'switch, toggle, on, off',
                'seoDescription' => 'Implement toggle switches with Flexiwind\'s accessible switch component.',
            ],
            [
                'title' => 'Table',
                'path' => '/components/table',
                'description' => 'Table for displaying data.',
                'keywords' => 'table, data, display',
                'seoDescription' => 'Display tabular data with Flexiwind\'s table component.',
            ],
            [
                'title' => 'Tabs',
                'path' => '/components/tabs',
                'description' => 'Navigation for multiple pages.',
                'keywords' => 'tabs, navigation, pages',
                'seoDescription' => 'Create tabbed interfaces with Flexiwind\'s tabs component.',
            ],
            [
                'title' => 'Text Area',
                'path' => '/components/text-area',
                'description' => 'Form input for user.',
                'keywords' => 'text area, form, user',
                'seoDescription' => 'Add multiline text inputs with Flexiwind\'s text area component.',
            ],
            [
                'title' => 'Tooltip',
                'path' => '/components/tooltip',
                'description' => 'Information for user on hover.',
                'keywords' => 'tooltip, information, hover',
                'seoDescription' => 'Add helpful tooltips to elements with Flexiwind\'s tooltip component.',
            ],
        ],
    ],
    [
        'label' => 'Layout',
        'items' => [
            [
                'title' => 'Container',
                'path' => '/docs/introduction',
                'description' => '',
                'keywords' => '',
                'state' => 'draft',
                'seoDescription' => 'Learn about Flexiwind\'s container component for consistent layout management.',
            ],
            [
                'title' => 'Grid',
                'path' => '/docs/installation',
                'description' => '',
                'keywords' => '',
                'state' => 'draft',
                'seoDescription' => 'Create responsive layouts with Flexiwind\'s grid system.',
            ],
        ],
    ],
];
